apiVersion: v2
name: kubeklipper
description: A Helm chart for Kubernetes

type: application

# Chart.Version defined on this file is unused. Instead, it is populated at package/publish time from the git tag being
# published.
version: 0.0.0

dependencies:
  - name: klipper
    version: 0.1.0
  - name: mainsail
    version: 0.1.0
    condition: mainsail.enabled
  - name: fluidd
    version: 0.1.0
    condition: fluidd.enabled
  - name: ustreamer
    version: 0.1.0
    condition: ustreamer.enabled
  - name: cura
    version: 0.1.0
    condition: cura.enabled
  - name: orcaslicer
    version: 0.1.0
    condition: orcaslicer.enabled
  - name: go2rtc
    version: 0.1.0
    condition: go2rtc.enabled
