apiVersion: v2
name: kubeklipper
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# Chart.Version defined on this file is unused. Instead, it is populated at package/publish time from the git tag being
# published.
version: 0.0.0

dependencies:
  - name: klipper
    version: 0.1.0
  - name: mainsail
    version: 0.1.0
    condition: mainsail.enabled
  - name: fluidd
    version: 0.1.0
    condition: fluidd.enabled
  - name: ustreamer
    version: 0.1.0
    condition: ustreamer.enabled
  - name: cura
    version: 0.1.0
    condition: cura.enabled
  - name: go2rtc
    version: 0.1.0
    condition: go2rtc.enabled
